config/routes.rb
Rails.application.routes.draw do
  resources :groups, only: [:index, :show], constraints: { id: /[^\/]+/ } do
    resources :projects, only: [:index, :show], constraints: { id: /\S+/ } do
      get :bugs_by_team
      get :bugs_by_severity
      get :bugs_by_priority
      get :feature_proposals_by_team
      get :issues_by_state
      get :regressions
      get :missed_deliverables
      get :bug_classification
      get :developer_productivity_metrics
      resources :teams, only: [:show]
    end

    get :bugs_by_team
    get :bugs_by_severity
    get :bugs_by_priority
    get :feature_proposals_by_team
    get :issues_by_state
    get :regressions
    get :missed_deliverables
    get :bug_classification
    get :developer_productivity_metrics
    resources :teams, only: [:show]
  end

  root 'groups#index'

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :projects
  has_many :issues, through: :projects
  has_many :merge_requests, through: :projects

  validates :path, uniqueness: true

  def full_path
    path
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project

  def age_in_days
    (Date.today - created_at).to_i
  end

  def age_in_months
    age_in_days / 30
  end
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :project
end

app/models/merge_request.rb
class MergeRequest < ActiveRecord::Base
  belongs_to :project
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :project
end

app/models/pipeline.rb
class Pipeline < ActiveRecord::Base
  belongs_to :project
end

app/models/project.rb
class Project  < ActiveRecord::Base
  belongs_to :group
  has_many :revisions

  has_many :issues
  has_many :labels
  has_many :merge_requests
  has_many :milestones
  has_many :pipelines

  validates :path, uniqueness: true

  def full_path
    "#{group.path}/#{path}"
  end

  def latest_revision
    revisions.last
  end
end

app/models/revision.rb
class Revision < ActiveRecord::Base
  belongs_to :project

  def to_s
    created_at.strftime('%d %B %Y %H:%M %Z')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = GitlabInsightsDashboardSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group

  def index
    @groups = Group.all
  end

  def show
    @projects = @group.projects
  end

  def find_group
    @group = Group.find_by(path: params[:group_id] || params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_group
  before_action :find_project, except: [:index]

  def index
    @projects = @group.projects
  end

  def find_group
    @group = Group.find_by(path: params[:group_id])
  end

  def find_project
    @project = @group.projects.find_by(path: params[:project_id] || params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ProjectsController
  TEAMS = {
    'ci/cd' => 'CI/CD'
  }

  before_action :find_group
  before_action :find_project

  def show
    @source = @project || @group
    @team = TEAMS[params[:id]] || params[:id].titleize
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/groups/bug_classification.html.haml
= render partial: 'shared/bug_classification', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'bug classification', link: method(:group_project_bug_classification_path) }

app/views/groups/bugs_by_priority.html.haml
= render partial: 'shared/bugs_by_priority', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'bugs by priority', link: method(:group_project_bugs_by_priority_path) }

app/views/groups/bugs_by_severity.html.haml
= render partial: 'shared/bugs_by_severity', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'bugs by severity', link: method(:group_project_bugs_by_severity_path) }

app/views/groups/bugs_by_team.html.haml
= render partial: 'shared/bugs_by_team', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'bugs by team', link: method(:group_project_bugs_by_team_path) }

app/views/groups/developer_productivity_metrics.haml
= render partial: 'shared/developer_productivity_metrics', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'developer productivity metrics', link: method(:group_project_developer_productivity_metrics_path) }

app/views/groups/feature_proposals_by_team.html.haml
= render partial: 'shared/feature_proposals_by_team', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'feature proposals by team', link: method(:group_project_feature_proposals_by_team_path) }

app/views/groups/index.html.haml
.container
  .page-header
    %h1.page-title Available Groups
  .row
    .list-group
      - @groups.each do |group|
        = link_to group.path, group_path(group.path), class: 'list-group-item'

app/views/groups/issues_by_state.html.haml
= render partial: 'shared/issues_by_state', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'issues by state', link: method(:group_project_issues_by_state_path) }

app/views/groups/missed_deliverables.html.haml
= render partial: 'shared/missed_deliverables', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'missed deliverables', link: method(:group_project_missed_deliverables_path) }

app/views/groups/regressions.html.haml
= render partial: 'shared/regressions', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'regressions', link: method(:group_project_regressions_path) }

app/views/groups/show.html.haml
.container
  .page-header
    %h1.page-title= "Group Dashboard: #{@group.path}"
  .row
    .col-md-6.col-lg-4
      .list-group
        = link_to 'Available Projects', group_projects_path(@group.path), class: 'list-group-item'
  .row
    .col-md-6.col-lg-4
      %h3.page-title Team views (group-level)
      .list-group
        = link_to 'Plan', group_team_path(@group.path, 'plan'), class: 'list-group-item'
        = link_to 'Create', group_team_path(@group.path, 'create'), class: 'list-group-item'
        = link_to 'Manage', group_team_path(@group.path, 'manage'), class: 'list-group-item'
        = link_to 'Verify', group_team_path(@group.path, 'verify'), class: 'list-group-item'
        = link_to 'Configure', group_team_path(@group.path, 'configure'), class: 'list-group-item'
        = link_to 'Documentation', group_team_path(@group.path, 'documentation'), class: 'list-group-item'
        = link_to 'Packaging', group_team_path(@group.path, 'packaging'), class: 'list-group-item'
        = link_to 'Release', group_team_path(@group.path, 'release'), class: 'list-group-item'
        = link_to 'Monitoring', group_team_path(@group.path, 'monitoring'), class: 'list-group-item'
        = link_to 'Secure', group_team_path(@group.path, 'secure'), class: 'list-group-item'
        = link_to 'Distribution', group_team_path(@group.path, 'distribution'), class: 'list-group-item'
        = link_to 'Gitaly', group_team_path(@group.path, 'gitaly'), class: 'list-group-item'
        = link_to 'Geo', group_team_path(@group.path, 'geo'), class: 'list-group-item'
        = link_to 'Quality', group_team_path(@group.path, 'quality'), class: 'list-group-item'
    .col-md-6.col-lg-4
      %h3.page-title Group views
      .list-group
        = link_to 'Bugs By Team', group_bugs_by_team_path(@group.path), class: 'list-group-item'
        = link_to 'Bugs By Severity', group_bugs_by_severity_path(@group.path), class: 'list-group-item'
        = link_to 'Bugs By Priority', group_bugs_by_priority_path(@group.path), class: 'list-group-item'
        = link_to 'Bug Classification', group_bug_classification_path(@group.path), class: 'list-group-item'
        = link_to 'Feature Proposals by Team', group_feature_proposals_by_team_path(@group.path), class: 'list-group-item'
        = link_to 'Issues by State', group_issues_by_state_path(@group.path), class: 'list-group-item'
        = link_to 'Regressions', group_regressions_path(@group.path), class: 'list-group-item'
        = link_to 'Missed Deliverables', group_missed_deliverables_path(@group.path), class: 'list-group-item'
        = link_to 'Developer Productivity Metrics', group_developer_productivity_metrics_path(@group.path), class: 'list-group-item'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GitLab Quality Dashboard
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .header.py-4
      .container
        .d-flex
          = link_to 'Insights', groups_path, class: 'header-brand'
    .header.collapse.d-lg-flex.p-0
      .container
        .row.align-items-center
          .col-lg-3.ml-auto
            - if @project && @project.latest_revision
              %div
                = "Last updated: #{@project.latest_revision}"
          .col-lg.order-lg-first
            %ul.nav.nav-tabs.border-0.flex-column.flex-lg-row
              %li.nav-item
                = link_to 'Groups', groups_path, class: 'nav-link'
              - if @group
                %li.nav-item >
                %li.nav-item
                  = link_to @group.path, group_path(@group.path), class: 'nav-link'
              - if @project
                %li.nav-item >
                %li.nav-item
                  = link_to 'Projects', group_projects_path(@group.path), class: 'nav-link'
                %li.nav-item >
                %li.nav-item
                  = link_to @project.path, group_project_path(@group.path, @project.path), class: 'nav-link'
    .page
      .page-main
        .my-3.my-md-5
          - if @group && !@project
            = hidden_field_tag "group_path", @group.path, { :id=> "group-path" }
          - if @project
            = hidden_field_tag "group_path", @project.group.path, { :id=> "group-path" }
            = hidden_field_tag "project_path", @project.path, { :id=> "project-path" }
          = yield

app/views/projects/bug_classification.html.haml
= render partial: 'shared/bug_classification', locals: { source: @project }

app/views/projects/bugs_by_priority.html.haml
= render partial: 'shared/bugs_by_priority', locals: { source: @project }

app/views/projects/bugs_by_severity.html.haml
= render partial: 'shared/bugs_by_severity', locals: { source: @project }

app/views/projects/bugs_by_team.html.haml
= render partial: 'shared/bugs_by_team', locals: { source: @project }

app/views/projects/developer_productivity_metrics.haml
= render partial: 'shared/developer_productivity_metrics', locals: { source: @project }

app/views/projects/feature_proposals_by_team.html.haml
= render partial: 'shared/feature_proposals_by_team', locals: { source: @project }

app/views/projects/index.html.haml
.container
  .page-header
    %h1.page-title= "Group Dashboard: #{@group.path} projects"
  .row
    .col-md-6.col-lg-4
      %h3.page-title Available Projects
      .list-group
        - @projects.each do |project|
          = link_to project.path, group_project_path(@group.path, project.path), class: 'list-group-item'

app/views/projects/issues_by_state.html.haml
= render partial: 'shared/issues_by_state', locals: { source: @project }

app/views/projects/missed_deliverables.html.haml
= render partial: 'shared/missed_deliverables', locals: { source: @project }

app/views/projects/regressions.html.haml
= render partial: 'shared/regressions', locals: { source: @project }

app/views/projects/show.html.haml
.container
  .page-header
    %h1.page-title= "Project Dashboard: #{@project.path}"
  .page-header
    %h2.page-title Available views
  .row
    .col-md-6.col-lg-4
      %h3.page-title Team views
      .list-group
        = link_to 'Plan', group_project_team_path(@group.path, @project.path, 'plan'), class: 'list-group-item'
        = link_to 'Create', group_project_team_path(@group.path, @project.path, 'create'), class: 'list-group-item'
        = link_to 'Manage', group_project_team_path(@group.path, @project.path, 'manage'), class: 'list-group-item'
        = link_to 'Verify', group_project_team_path(@group.path, @project.path, 'verify'), class: 'list-group-item'
        = link_to 'Configure', group_project_team_path(@group.path, @project.path, 'configure'), class: 'list-group-item'
        = link_to 'Documentation', group_project_team_path(@group.path, @project.path, 'documentation'), class: 'list-group-item'
        = link_to 'Packaging', group_project_team_path(@group.path, @project.path, 'packaging'), class: 'list-group-item'
        = link_to 'Release', group_project_team_path(@group.path, @project.path, 'release'), class: 'list-group-item'
        = link_to 'Monitoring', group_project_team_path(@group.path, @project.path, 'monitoring'), class: 'list-group-item'
        = link_to 'Secure', group_project_team_path(@group.path, @project.path, 'secure'), class: 'list-group-item'
        = link_to 'Distribution', group_project_team_path(@group.path, @project.path, 'distribution'), class: 'list-group-item'
        = link_to 'Gitaly', group_project_team_path(@group.path, @project.path, 'gitaly'), class: 'list-group-item'
        = link_to 'Geo', group_project_team_path(@group.path, @project.path, 'geo'), class: 'list-group-item'
        = link_to 'Quality', group_project_team_path(@group.path, @project.path, 'quality'), class: 'list-group-item'
    .col-md-6.col-lg-4
      %h3.page-title Project views
      .list-group
        = link_to 'Bugs By Team', group_project_bugs_by_team_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Bugs By Severity', group_project_bugs_by_severity_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Bugs By Priority', group_project_bugs_by_priority_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Bug Classification', group_project_bug_classification_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Feature Proposals by Team', group_project_feature_proposals_by_team_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Issues by State', group_project_issues_by_state_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Regressions', group_project_regressions_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Missed Deliverables', group_project_missed_deliverables_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Developer Productivity Metrics', group_project_developer_productivity_metrics_path(@group.path, @project.path), class: 'list-group-item'

app/views/shared/_bug_classification.html.haml
.container
  .page-header
    %h1.page-title= "Dashboard: #{source.path}"
  .page-header
    %h2.page-title Bugs Classification
  .row.row-cards
    .col-6.col-sm-4.col-lg-2
      .card
        .card-body.p-3.text-center
          #bugs-severity-number
            .total.h1.m-0 0
          .text-muted.mb-4 Percentage Open Bugs Severitized
    .col-6.col-sm-4.col-lg-2
      .card
        .card-body.p-3.text-center
          #bugs-priority-number
            .total.h1.m-0 0
          .text-muted.mb-4 Percentage Open Bugs Prioritized
  .row.row-cards
    .col-md-6.col-lg-6
      .card
        .card-header
          %h3.card-title Open Bugs by Severity
        %canvas#bugs-severity-pie
    .col-md-6.col-lg-6
      .card
        .card-header
          %h3.card-title Open Bugs by Priority
        %canvas#bugs-priority-pie

app/views/shared/_bugs_by_priority.html.haml
.container
  .page-header
    %h1.page-title= "Dashboard: #{source.path}"
  .page-header
    %h2.page-title Bugs By Priority
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Cumulative Open bugs by Priority
        %canvas#cumulative-bugs-created-priority-month
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Open bugs by Priority
        %canvas#bugs-created-priority-month
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Closed bugs by Priority
        %canvas#bugs-closed-priority-month

app/views/shared/_bugs_by_severity.html.haml
.container
  .page-header
    %h1.page-title= "Dashboard: #{source.path}"
  .page-header
    %h2.page-title Bugs By Severity
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Cumulative Open bugs by Severity
        %canvas#cumulative-bugs-created-severity-month
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Open bugs by Severity
        %canvas#bugs-created-severity-month
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Closed bugs by Severity
        %canvas#bugs-closed-severity-month

app/views/shared/_bugs_by_team.html.haml
.container
  .page-header
    %h1.page-title= "Dashboard: #{source.path}"
  .page-header
    %h2.page-title Bugs By Team
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Cumulative Bugs Created Per Month Per Team
        %canvas#cumulative-bugs-created-per-month
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Bugs Created Per Month Per Team
        %canvas#bugs-created-per-month
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Bugs Closed Per Month Per Team
        %canvas#bugs-closed-per-month
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Bugs Created Per Day Per Team
        %canvas#bugs-created-per-day
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Bugs Closed Per Day Per Team
        %canvas#bugs-closed-per-day

app/views/shared/_developer_productivity_metrics.haml
.container
  .page-header
    %h1.page-title= "Dashboard: #{source.path}"
  .page-header
    %h2.page-title Developer Productivity Metrics
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Average MRs Merged Per Author Per Milestone (team only)
        %canvas#average-mrs-milestone-team
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Average MRs Merged Per Author Per Milestone (including community)
        %canvas#average-mrs-milestone-all

app/views/shared/_feature_proposals_by_team.html.haml
.container
  .page-header
    %h1.page-title= "Dashboard: #{source.path}"
  .page-header
    %h2.page-title Feature Proposal by Team
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Feature Proposal Created Per Month Per Team
        %canvas#proposals-created-per-month
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Feature Proposals Closed Per Month Per Team
        %canvas#proposals-closed-per-month

app/views/shared/_issues_by_state.html.haml
.container
  .page-header
    %h1.page-title= "Dashboard: #{source.path}"
  .page-header
    %h2.page-title Issues by State
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Issues Opened vs Closed Per Month
        %canvas#issues-opened-closed-month

app/views/shared/_missed_deliverables.html.haml
.container
  .page-header
    %h1.page-title= "Dashboard: #{source.path}"
  .page-header
    %h2.page-title Missed Deliverables
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Missed Deliverables Per Milestone
        %canvas#missed-deliverables-per-milestone

app/views/shared/_project_level_links.html.haml
- id = local_assigns.fetch(:id, nil)

.container
  .row.row-cards
    .col-lg-12
      %h3.page-title Associated project-level views
      .list-group
        - group.projects.each do |project|
          = link_to "#{project.path} #{name}", link.call(group.path, project.path, id), class: 'list-group-item'

app/views/shared/_regressions.html.haml
.container
  .page-header
    %h1.page-title= "Dashboard: #{source.path}"
  .page-header
    %h2.page-title Regressions
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Regressions Per Milestone
        %canvas#regressions-per-milestone